#!/usr/bin/env sh
# Deterministically ensure ./gradlew exists by copying from gradlew.template.sh
set -e
TEMPLATE="./gradlew.template.sh"
TARGET="./gradlew"

if [ ! -f "$TEMPLATE" ]; then
  echo "[init-gradlew] ERROR: Missing $TEMPLATE"
  # Fallback: write a minimal stub
  cat > "$TARGET" <<'EOF'
#!/usr/bin/env sh
echo "[CI stub] ./gradlew generated by init-gradlew; Expo managed repo."
exit 0
EOF
else
  cp "$TEMPLATE" "$TARGET"
fi

chmod +x "$TARGET" 2>/dev/null || true
echo "[init-gradlew] Wrote $TARGET and set executable."
exit 0
